# Generated by Django 4.2.1 on 2023-06-26 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0019_alter_order_survery_q6'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stay_duration',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
