# Generated by Django 4.2.1 on 2023-06-26 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0021_remove_order_stay_duration_airline_stay_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airline',
            name='stay_duration',
        ),
        migrations.AddField(
            model_name='order',
            name='stay_duration',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
