# Generated by Django 4.2.1 on 2023-07-03 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0025_order_stay_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stay_duration',
        ),
    ]
