# Generated by Django 4.2.1 on 2023-07-26 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0027_order_subject_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='subject_income',
            field=models.CharField(default='-', max_length=10),
        ),
    ]
