# Generated by Django 4.2.1 on 2023-07-03 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0024_remove_order_stay_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stay_duration',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
