# Generated by Django 4.2.1 on 2023-07-10 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0026_remove_order_stay_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='subject_education',
            field=models.CharField(default='-', max_length=10),
        ),
    ]
